### ISSUE TITLE
是否能支持类似vue-i18n的全局注入配置

### ISSUE THREAD

**Issue by Rushhhhh** [aaronlamz/vue-next-i18n#8]
![image](https://user-images.githubusercontent.com/35788339/230577084-6ed9ece3-19b2-456f-bc0f-adc354d48c2b.png)

全局注入
globalInjection: true,

**Comment by aaronlamz** [comment]
这个已经默认支持的了，目前支持全局$t方法

**Comment by Magisk2** [comment]
打包构建的时候报错,$t不存在
![image](https://github.com/aaronlamz/vue-next-i18n/assets/51899007/4433aa8f-973c-41c3-80e1-1519a25cc0f7)

**Comment by aaronlamz** [comment]
本地跑没问题？可以提供下复现demo

**Comment by Magisk2** [comment]
> 本地跑没问题？可以提供下复现demo

本地跑没有任何问题，只有在打包的时候才会报错。这是一个可复现的demo： https://github.com/Magisk2/vue-next-i18n-demo

**Comment by aaronlamz** [comment]
好的，我看一下

**Comment by aaronlamz** [comment]
> > 本地跑没问题？可以提供下复现demo
> 
> 本地跑没有任何问题，只有在打包的时候才会报错。这是一个可复现的demo： https://github.com/Magisk2/vue-next-i18n-demo

v1.0.14 已修复
